### ISSUE TITLE
Switching orientation crashes the app

### ISSUE THREAD

**Issue by NickTUD** [foresterre/ContextProject#72]
```06-17 15:44:30.000  10759-10777/cg.group4.android E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 974
    java.lang.NullPointerException
            at cg.group4.view.screen.CollectiblesScreen.constructContents(CollectiblesScreen.java:235)
            at cg.group4.view.screen.CollectiblesScreen.rebuildWidgetGroup(CollectiblesScreen.java:94)
            at cg.group4.view.screen_mechanics.ScreenStore.rebuild(ScreenStore.java:139)
            at cg.group4.view.screen_mechanics.WorldRenderer.resize(WorldRenderer.java:165)
            at com.badlogic.gdx.Game.resize(Game.java:51)
            at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:247)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)```

**Comment by NickTUD** [comment]
Switching from Landscape to Portrait and vice versa. No matter what screen you are in.
