### ISSUE TITLE
FishingStrollEvent crashes upon initialisation

### ISSUE THREAD

**Issue by NickTUD** [foresterre/ContextProject#73]
```06-17 15:52:41.070  11209-11228/cg.group4.android E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 983
    java.lang.NullPointerException
            at cg.group4.game_logic.stroll.events.fishevent.FishingStrollEvent.update(FishingStrollEvent.java:51)
            at java.util.Observable.notifyObservers(Observable.java:138)
            at cg.group4.data_structures.subscribe.Subject.update(Subject.java:27)
            at cg.group4.game_logic.StandUp.update(StandUp.java:131)
            at cg.group4.Launcher.render(Launcher.java:152)
            at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
06-17 15:52:45.210  11209-11209/cg.group4.android E/AndroidGraphics﹕ waiting for pause synchronization took too long; assuming deadlock and killing```

**Comment by NickTUD** [comment]
It seems that the update() method gets called before the start() method for some reason
